name: CI/CD - Deploy to EC2 via Docker Hub (Development)

on:
  push:
    branches:
      - Development  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ecommerce-payment-api
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:dev .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:dev

      - name: Deploy to EC2 (Development)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-payment-api:dev
            sudo docker stop ecommerce-payment-api || true
            sudo docker rm ecommerce-payment-api || true
            sudo docker run -d -p 3000:3000 --name ecommerce-payment-api ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-payment-api:dev
